### ISSUE TITLE
Styling of checkboxes related to hiding information

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#10]
Hide check box can be given next to the text box header. we need to have separate space for it.

**Comment by mckdev** [comment]
Can you be more specific? I don't get what this ticket is about.

**Comment by jananihome** [comment]
![capture1](https://user-images.githubusercontent.com/31224232/30182847-e5cec096-9435-11e7-9ebf-cc69c8d079f5.PNG)

Red area content can be replace in blue area so that we will optimize the space and scrolling size.

**Comment by mckdev** [comment]
Not sure if this can be done exactly like you say, because these are separate form inputs, but I will try to make it at least more compact.

**Comment by jananihome** [comment]
ok

**Comment by jananihome** [comment]
By default hide check box should be enabled. Only if they want to display they should disable it.

**Comment by mckdev** [comment]
I will implement an easy solution for now, how I did in educational need form:
![image](https://user-images.githubusercontent.com/17580930/30513240-72ea3994-9b00-11e7-9d7d-68c8526f65bb.png)

**Comment by mckdev** [comment]
Here it is:
![image](https://user-images.githubusercontent.com/17580930/30513301-5b8072c2-9b01-11e7-8801-9c5785c83bf1.png)

**Comment by jananihome** [comment]
ok
