### ISSUE TITLE
Share option

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#107]
Need to have share option in card view as well as details view.
Share option for whatsapp, fb, twitter and insta.
Both card view and detail shared link should open detail view only.
In card view just above the unique ID we can have sharing icons for different social media platform.
In detail view below amount required we can use it. Below that we can use entire width of the card for this.

**Comment by mckdev** [comment]
https://github.com/jananihome/Janani-Home/pull/109
