### ISSUE TITLE
Resizing issue

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#11]
When resizing the logo and title does not align according to the size. That part is misbehaving.

**Comment by mckdev** [comment]
Can you be more specific and post a screenshot?

**Comment by jananihome** [comment]
![capture](https://user-images.githubusercontent.com/31224232/30182681-51d8a3ac-9435-11e7-81e9-f598c1647886.PNG)
This is what i meant.
!

**Comment by mckdev** [comment]
Cool, thanks, I will see what I can do

**Comment by mckdev** [comment]
The best solution here is to hide the image for very small screen sizes, because with how menu grid is structured now, I really don't see how solve this. The header will probably be changed anyway so for now I will hide the logo for very small screens so it looks good.
