### ISSUE TITLE
Description text area

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#13]
Instead of plain text we need to us CL editor.

**Comment by mckdev** [comment]
Ok I will implement ckeditor: https://github.com/django-ckeditor/django-ckeditor

**Comment by jananihome** [comment]
i dont know what it looks like can you send me a link to of it actually looks like.

**Comment by mckdev** [comment]
It is really the best performing rich text editor for Django, I tested many of them. We can customize how it looks and which options it has.

**Comment by jananihome** [comment]
can we create tables kind of stuff?

**Comment by mckdev** [comment]
Yes, basically anything Word can do, but we can limit the options.
