### ISSUE TITLE
Signup page style

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#16]
Signup page input fields are also wider. Can be compact.

**Comment by mckdev** [comment]
For now I've made it like this:
![image](https://user-images.githubusercontent.com/17580930/30513381-878a95cc-9b02-11e7-8248-99ed64003390.png)

@jananihome Can we close this ticket and continue further work in #33 ?

**Comment by jananihome** [comment]
Its fine now.

**Comment by mckdev** [comment]
Thanks
