### ISSUE TITLE
Hide addresses in educational need

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#3]
Address bar hide option.

**Comment by mckdev** [comment]
Which parts of address should be hidden and which not?

**Comment by jananihome** [comment]
both should have that option. The thing which we enter in address field.

**Comment by mckdev** [comment]
I still don't get it. You mean address in edit profile or addresses in educational need.

**Comment by jananihome** [comment]
In educational need address. And education need address need to be aligned like edit profile.

**Comment by mckdev** [comment]
Ok now all clear
