### ISSUE TITLE
Unique id display

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#30]
Need to bring unique id in cards as well other views for users.

**Comment by jananihome** [comment]
Unique Id bring to the top part and make it visible boldy. Do not keep them in corner with low shades.

**Comment by mckdev** [comment]
Yeah but they look ugly... where exactly to the top part? Also on list view or you mean the detail view only?

**Comment by mckdev** [comment]
List view after change
![image](https://user-images.githubusercontent.com/17580930/30521442-f7cf4900-9bbf-11e7-927b-6f69c9ff2b9e.png)

**Comment by mckdev** [comment]
And detail view:
![image](https://user-images.githubusercontent.com/17580930/30521476-5b16f5c6-9bc0-11e7-8a5c-e54829e17414.png)

**Comment by jananihome** [comment]
Detail view id also make it as dark black.

**Comment by mckdev** [comment]
It is black.
