### ISSUE TITLE
Educational Need detail view style

### ISSUE THREAD

**Issue by mckdev** [jananihome/Janani-Home#32]
Educational Need detail view needs a complete redesign:
http://jananihome.pythonanywhere.com/educational_need/12/

I need a list of requirements and instructions on how to do it:
- some example of the layout would be useful
- what information to display and what not to display (currently we are not displaying much)

**Comment by mckdev** [comment]
For now I have done something like this:
![image](https://user-images.githubusercontent.com/17580930/30514617-1bc622e0-9b19-11e7-893e-41dd4b9a8052.png)
Let me know where to go from here or if it is good, then  let's close this ticket.

**Comment by mckdev** [comment]
You can see the new version live here:
http://jananihome.pythonanywhere.com/educational_need/7/

**Comment by jananihome** [comment]
We will leave as it is now. Let us get the feedback from the users and will decide on it.

**Comment by mckdev** [comment]
Cool, I will only fix the "Age" field, because we need to calculate the age from the birth year here.

**Comment by jananihome** [comment]
OK
