### ISSUE TITLE
Need to decide which tools to leave for rich text descriptions

### ISSUE THREAD

**Issue by mckdev** [jananihome/Janani-Home#38]
Currently there is too many options enabled in CKeditor. We don't need 90% of them.

**Comment by jananihome** [comment]
Save, New Page, Preview, Print, Button, Hidden Field, Div Container, Set Language, Insert Image, Media Embedded, Flash, Insert Page Break For Printing, Iframe, Form, About CK editor, Show Blocks, Radio Button, Check Box,  Selection Field, Text Field, Text Area, Paste From Word.

All these things can be removed.
