### ISSUE TITLE
Header & navbar style

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#4]
Can have header title and sub title at top center of the page and educational need below that  after logo.

**Comment by mckdev** [comment]
Can you be more specific - I don't really understand.

**Comment by jananihome** [comment]
I mean Janani Home in top center, below that Mothers love and care.Below that search bar and after that
in the left hand side educational need menu. When we hover the menu highlight it. Applicable for every thing login, logout, signup(make them some what brighter compared to what we have).

**Comment by mckdev** [comment]
I think I will need a sketch here because I cannot imagine it.

**Comment by mckdev** [comment]
What about this:
![image](https://user-images.githubusercontent.com/17580930/30514837-1b7c4216-9b1d-11e7-81f1-e3918fcefdf7.png)

**Comment by mckdev** [comment]
I did a few more changes, it is live on http://jananihome.pythonanywhere.com/

**Comment by jananihome** [comment]
This looks fine.

**Comment by mckdev** [comment]
Great!
