### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#57]
Our website doesn't come in google search.

**Comment by mckdev** [comment]
We need to create Webmaster Tools account:
https://www.google.com/webmasters/#?modal_active=none

I can take care.

**Comment by mckdev** [comment]
I checked and Google already displays results for site:jananihome.com after we submitted the URL.
I have also created GWT account with our Google account: https://www.google.com/webmasters/tools/
We will have to follow up with additional tickets, I have already create in project SEO: https://github.com/jananihome/Janani-Home/projects/1#card-4872183
