### ISSUE TITLE
Verified by 

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#77]
For verified by use same color as you used for address and in detail view bring that just below published date with small fonts, not in between two lines. We need to have two lines.Published followed by verified in small font and then line and view count.

**Comment by mckdev** [comment]
![image](https://user-images.githubusercontent.com/17580930/34391110-351613ec-eb44-11e7-8081-0d4d0bbe4254.png)
![image](https://user-images.githubusercontent.com/17580930/34391118-3bf0d56c-eb44-11e7-8388-ae8b946c97fc.png)
