### ISSUE TITLE
Educational need icon

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#8]
https://www.w3schools.com/icons/tryit.asp?filename=trybs_ref_glyph_education

use this link and get the icon.

**Comment by mckdev** [comment]
Glyphicons are deprecated in newer versions of Bootstrap so we need to use font-awesome. I will use this icon (it's the same): http://fontawesome.io/icon/graduation-cap/

**Comment by jananihome** [comment]
ok fine. This is also good.

**Comment by jananihome** [comment]
so here after glyphicons are deprecated?
Is font awesome the official support icon for bootstrap?

**Comment by mckdev** [comment]
Bootstrap removed icons completely in new versions, and since there is no easy way to get Glyphicons without using old Bootstrap, font-awesome is the recommended replacement for Glyphicon now.

**Comment by mckdev** [comment]
Also all the current icons we are using are from font-awesome so adding new is very easy.

**Comment by jananihome** [comment]
ok.
