### ISSUE TITLE
Adding Volunteers

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#85]
Once NGO registration approved by admin he should able to add volunteers.
The volunteers should be mapped with respective organisation.
The volunteer detail should be same as user, but if he wants to if he joins as volunteers he/she should be able to select the organisation in which he want to join .
Once he selects while signing up it should go to the respective organisation for approval. 
After approved his profile should be made as active with respective organisation.
If he wants to relieve from respective org he he/she should raise a request and it should be approved by org. Then he/she can change join another org.
Apart from this organisation should have option to create or delete volunteers on behalf of the users.
We need to follow UI master detail design pattern for this.

The above thing is for adding volunteers only. Once its done it next process will be started.

**Comment by jananihome** [comment]
1.Dashboard to approve the list of pending ngo request and comment approval.
2User should create a profile and request ngo to join them and vice versa ngo can request to join in their org. 
3.If request made by ngo to the user, user should get mail and a notification to accept or reject the request in the website.
4.User cannot e part of more than one ngo. If he want to join new ngo user should deactivate from existing and request a new one. Similarly ngo should not have the name in the list if he is part of another ngo.,
5.Only if user accepts ngo invitation user should be made as active volunteer.

**Comment by mckdev** [comment]
Hi,

thanks for the ticket. I suggest we implement it in 4 steps, in this order:

1. NGOs should be able to browse registered users and invite them to become their volunteers.
2. Registered users should be able to browse registered NGOs and apply to become volunteers.
3. NGOs should be able to create new user accounts, auto-approved as their volunteers.
4. There should be a way for users to cancel cooperation with NGO.

Please confirm that this is what you wanted and create separate tickets for each step with details.

**Comment by mckdev** [comment]
Closing this as we have it split into smaller tickets now.
