### ISSUE TITLE
Registered users should be able to browse registered NGOs and apply to become volunteers.

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#89]
Refer Ticket 85

Once NGO registration approved by admin he should able to add volunteers.
The volunteers should be mapped with respective organisation.
The volunteer detail should be same as user, but if he wants to if he joins as volunteers he/she should be able to select the organisation in which he want to join .
Once he selects while signing up it should go to the respective organisation for approval.
After approved his profile should be made as active with respective organisation.

**Comment by mckdev** [comment]
This is done already.
