### ISSUE TITLE
User cannot be part of more than one ngo

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#91]
If he want to join new ngo user should deactivate from existing and request a new one. Similarly ngo should not have the name in the list if he is part of another ngo.,

Refer ticket 85

If he wants to relieve from respective org he he/she should raise a request and it should be approved by org. Then he/she can change join another org.

**Comment by mckdev** [comment]
User already cannot belong to more than one NGO. It is guaranteed by db design.

As for:

> If he wants to relieve from respective org he he/she should raise a request and it should be approved by org. Then he/she can change join another org.

It will be handled in #96. Closing this.
